import streamlit as st
import yfinance as yf
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression

# --- 1. TERMINAL UI STYLING ---
st.set_page_config(page_title="QuantYield Terminal", layout="wide")

st.markdown("""
    <style>
    .stApp { background-color: #0d1117; color: #c9d1d9; }
    h1 { color: #58a6ff !important; font-family: 'Roboto Mono', monospace; margin-bottom: 0px; }
    [data-testid="stMetricLabel"] { color: #7ee787 !important; font-family: 'Roboto Mono', monospace; }
    [data-testid="stMetricValue"] { color: #ffffff !important; font-family: 'Roboto Mono', monospace; }
    [data-testid="stSidebar"] { background-color: #161b22; border-right: 1px solid #30363d; }
    </style>
    """, unsafe_allow_html=True)

# --- 2. DATA ENGINE ---
@st.cache_data
def load_data():
    tickers = {"^IRX": "3M", "^TNX": "10Y", "^TYX": "30Y"}
    df = yf.download(list(tickers.keys()), period="5y", interval="1d")['Close'].rename(columns=tickers).dropna()
    return df

try:
    df = load_data()
    X = df[['3M', '30Y']]
    y = df['10Y']
    # The Core Instrument
    model = LinearRegression().fit(X, y)

    # --- 3. BRANDED HEADER & INSTRUMENT STATUS ---
    st.title("QuantYield: Predictive Yield Curve Engine <EXEC>")
    
    # THE SPECIFIC STATUS SENTENCE
    st.markdown("""
        <p style='font-family: "Roboto Mono", monospace; color: #58a6ff; font-size: 14px; margin-top: 5px; line-height: 1.6;'>
            <span style='color: #7ee787;'>●</span> <b>AI Engine Status:</b> OLS_REGRESSION_V1 is active. 
            Utilizing Ordinary Least Squares to synthesize historical priors with user-defined calibration.
        </p>
        """, unsafe_allow_html=True)
    st.markdown("---")

    # --- 4. CORE ANALYTICS ---
    c1, c2, c3, c4 = st.columns(4)
    curr_3m, curr_10y, curr_30y = df['3M'].iloc[-1], df['10Y'].iloc[-1], df['30Y'].iloc[-1]
    fair_val = model.predict([[curr_3m, curr_30y]])[0]

    c1.metric("MKT: 10Y", f"{curr_10y:.3f}%", help="Current market yield.")
    c2.metric("SYS: FAIR_VAL", f"{fair_val:.3f}%", delta=f"{fair_val - curr_10y:.3f}%", 
              help="The theoretical fair value derived by the OLS_REGRESSION_V1 instrument.")
    c3.metric("MOD: R-SQUARED", f"{model.score(X, y):.4f}", 
              help="Statistical confidence of the OLS fit.")
    c4.metric("SPR: 30Y-3M", f"{(curr_30y - curr_3m)*100:.1f} bps", 
              help="Slope of the current Treasury curve.")

    # --- 5. VISUALS ---
    st.subheader("<HIST> TIME_SERIES_ANALYSIS")
    st.line_chart(df, height=350)

    # --- 6. SIDEBAR: CALIBRATION ---
    st.sidebar.markdown("### <CMD> CALIBRATE_PRIORS")
    s_shock = st.sidebar.slider("Short-Term Shock (BPS)", -200, 200, 0) / 100
    l_shock = st.sidebar.slider("Long-Term Shock (BPS)", -200, 200, 0) / 100
    
    new_pred = model.predict([[curr_3m + s_shock, curr_30y + l_shock]])[0]
    st.sidebar.divider()
    st.sidebar.metric("Posterior Prediction", f"{new_pred:.3f}%")
    st.sidebar.info("Prediction generated by OLS_REGRESSION_V1 synthesis.")

    st.markdown("`STATUS: SYSTEM_READY | DATA_INTEGRITY_VERIFIED`")

except Exception as e:
    st.error(f"System Error: {e}")
